### ISSUE TITLE
Pytest coverage statistics reporting fails

### ISSUE THREAD

**Issue by stefanhartmann123** [JetBrains/teamcity-messages#218]
Running pytest coverage in teamcity with teamcity-messages fails with the following error:

![image](https://user-images.githubusercontent.com/14122401/61058356-5df38200-a3f7-11e9-812f-4b4d2f2bcdd4.png)

Using:
teamcity-messages 1.25
pytest-cov 2.7.1

Python version: 3.6.8

**Comment by enkelli** [comment]
I think this should be fixed in #226 but it already waits more than 1 month for merge :disappointed:

**Comment by angelomelonas** [comment]
I'm using `team-city` 1.28, `pytest-cov` 2.8.1 and I'm still getting the error above when running pytest.

**Comment by enkelli** [comment]
> 
> 
> I'm using `teamcity-messages 1.28`, `pytest-cov 2.8.1` and I'm still getting the error above when running pytest.

Hi, can you provide more details? Full output with the error message, `coverage` tool version, etc.?

**Comment by angelomelonas** [comment]
Hi @enkelli I was just about to add that using the setup above but then setting `coverage <5.0` gets rid of the error. I should also note I'm using `Python 3.6.9`, `pytest-5.4.1`, `sugar-0.9.3` and `cov-2.8.1`

The error (when using `coverage >= 5.0`):

```
Coverage statistics reporting failed
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/pytest_plugin.py", line 370, in pytest_terminal_summary
    self._report_coverage()
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/pytest_plugin.py", line 377, in _report_coverage
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter'
```

**Comment by enkelli** [comment]
Are you sure you've got `teamcity-messages==1.28`?
Your log says that line 377 in `pytest_plugin` contains: `from coverage.report import Reporter`. But line 377 is actually: `from coverage.misc import NotPython`.

Check `1.28` source code [here](https://github.com/JetBrains/teamcity-messages/blob/master/teamcity/pytest_plugin.py#L376) - the only import of `Reporter` class is handled correctly in `try-except`.

**Comment by angelomelonas** [comment]
@enkelli I specifically checked in my local libs now and my `teamcity` plugin says `__version__ = "1.28"`. I do see what you mean though. Line 377 is `from coverage.misc import NotPython` in `pytest_plugin.py`. That is very strange.
